export const genres = [
	{ label: 'Все жанры', value: '', checked: false },
	{ label: 'Семейные', value: 'семейный', checked: false },
	{ label: 'Биографии', value: 'биография', checked: false },
	{ label: 'Боевики', value: 'боевик', checked: false },
	{ label: 'Вестерны', value: 'вестерн', checked: false },
	{ label: 'Военные', value: 'военный', checked: false },
	{ label: 'Детективы', value: 'детектив', checked: false },
	{ label: 'Детские', value: 'детский', checked: false },
	{ label: 'Документальные', value: 'документальный', checked: false },
	{ label: 'Драмы', value: 'драма', checked: false },
	{ label: 'Исторические', value: 'история', checked: false },
	{ label: 'Комедии', value: 'комедия', checked: false },
	{ label: 'Короткометражки', value: 'короткометражка', checked: false },
	{ label: 'Криминал', value: 'криминал', checked: false },
	{ label: 'Мелодрамы', value: 'мелодрама', checked: false },
	{ label: 'Музыкальные', value: 'музыка', checked: false },
	{ label: 'Мюзиклы', value: 'мюзикл', checked: false },
	{ label: 'Новости', value: 'новости', checked: false },
	{ label: 'Приключения', value: 'приключения', checked: false },
	{ label: 'Спортивные', value: 'спорт', checked: false },
	{ label: 'Триллеры', value: 'триллер', checked: false },
	{ label: 'Ужасы', value: 'ужасы', checked: false },
	{ label: 'Фантастика', value: 'фантастика', checked: false },
	{ label: 'Фильмы-нуар', value: 'фильм-нуар', checked: false },
	{ label: 'Фэнтези', value: 'фэнтези', checked: false },
]
